/*-----------------------------------------------------------------------------*/
/* errors identifiers header file                                               */
/*                                                                             */
/* this file is automatically generated form excel sheet                       */
/*                                                                             */
/* author: egarcia                                                             */
/*-----------------------------------------------------------------------------*/
#ifndef R100_ERRORS
#define R100_ERRORS

/******************************************************************************
** includes
*/

#include "R100_Errors_cfg.h"

/******************************************************************************
** defines
*/

#define OK                           eERR_NONE
#define DATA_NOT_AVAILABLE      -1   ///< Data is not available
#define APP_ERR_TRAP(a)     if (a) {/*__BKPT(0); */Lock_on_Panic();}

#define MAX_ERRORS               256               /// number of errors

/******************************************************************************
** typedefs
*/

typedef enum
{
    eERR_NONE                  = 0,  /// 
    eERR_OPTION_DISABLED       = 1,  /// 
    eERR_NV_SZ                 = 2,  /// 
    /// free to use            = 3,
    eERR_NFC_INFO              = 4,  /// 
    eERR_ZP_DATA               = 5,  /// 
    eERR_AUDIO_MAX             = 6,  /// 
    /// free to use            = 7,
    /// free to use            = 8,
    /// free to use            = 9,
    eERR_DEF_CHARGING_FAST     = 10, /// 
    eERR_DEF_CHARGING_SLOW     = 11, /// 
    eERR_DEF_DISCHARGING_H     = 12, /// 
    eERR_DEF_DISCHARGING_R     = 13, /// 
    eERR_DEF_SHOCK             = 14, /// 
    eERR_DEF_CURRENT_SENSE     = 15, /// 
    /// free to use            = 16,
    /// free to use            = 17,
    /// free to use            = 18,
    /// free to use            = 19,
    eERR_ELECTRODE_EXPIRED     = 20, /// 
    eERR_ELECTRODE_USED        = 21, /// 
    eERR_ELECTRODE_NOT_CONNECTED  = 22,/// 
    /// free to use            = 23,
    /// free to use            = 24,
    /// free to use            = 25,
    /// free to use            = 26,
    /// free to use            = 27,
    /// free to use            = 28,
    /// free to use            = 29,
    eERR_BATTERY_EXPIRED       = 30, /// 
    eERR_BATTERY_UNKNOWN       = 31, /// 
    eERR_BATTERY_LOW           = 32, /// 
    eERR_BATTERY_REPLACE       = 33, /// 
    eERR_BATTERY_TEMP_OUT_RANGE  = 34,/// 
    eERR_BATTERY_TEMP_OUT_RANGE_OFF  = 35,/// 
    /// free to use            = 36,
    /// free to use            = 37,
    /// free to use            = 38,
    /// free to use            = 39,
    eERR_SMON_DCMAIN_TOO_HIGH  = 40, /// 
    eERR_SMON_DCMAIN_TOO_LOW   = 41, /// 
    eERR_SMON_18V_TOO_HIGH     = 42, /// 
    eERR_SMON_18V_TOO_LOW      = 43, /// 
    /// free to use            = 44,
    /// free to use            = 45,
    /// free to use            = 46,
    /// free to use            = 47,
    /// free to use            = 48,
    /// free to use            = 49,
    eERR_ADS_DEVICE_ID         = 50, /// 
    eERR_ADS_DEVICE_ACCESS     = 51, /// 
    eERR_ADS_CALIBRATION       = 52, /// 
    eERR_ADS_PAT_CONNECTED     = 53, /// 
    /// free to use            = 54,
    /// free to use            = 55,
    /// free to use            = 56,
    /// free to use            = 57,
    /// free to use            = 58,
    /// free to use            = 59,
    eERR_BOOT_PROCESSOR        = 60, /// 
    eERR_BOOT_NO_UPDATE        = 61, /// 
    eERR_BOOT_PROCESSOR_UPDATE = 62, /// 
    eERR_BOOT_SPI_MEMORY       = 63, /// 
    /// free to use            = 64,
    /// free to use            = 65,
    /// free to use            = 66,
    /// free to use            = 67,
    /// free to use            = 68,
    /// free to use            = 69,
    eERR_AUDIO_PLAYER          = 70, /// 
    eERR_AUDIO_QUEUE_FULL      = 71, /// 
    /// free to use            = 72,
    /// free to use            = 73,
    /// free to use            = 74,
    /// free to use            = 75,
    /// free to use            = 76,
    /// free to use            = 77,
    /// free to use            = 78,
    /// free to use            = 79,
    eERR_COMM_UART_SELECT      = 80, /// 
    eERR_COMM_UART_BAUD_RATE   = 81, /// 
    eERR_COMM_UART_RX_ERROR    = 82, /// 
    /// free to use            = 83,
    /// free to use            = 84,
    /// free to use            = 85,
    /// free to use            = 86,
    /// free to use            = 87,
    /// free to use            = 88,
    /// free to use            = 89,
    /// free to use            = 90,
    /// free to use            = 91,
    /// free to use            = 92,
    /// free to use            = 93,
    /// free to use            = 94,
    /// free to use            = 95,
    /// free to use            = 96,
    /// free to use            = 97,
    /// free to use            = 98,
    /// free to use            = 99,
    eERR_COMM_WIFI_INIT        = 100,/// 
    eERR_COMM_WIFI_CHECK_STATUS = 101,/// 
    eERR_COMM_WIFI_INIT_FACTORY_RESET_MAC    = 102,/// 
    eERR_COMM_WIFI_INIT_SYNC   = 103,/// 
    eERR_COMM_WIFI_INIT_CONFIG_HEADER = 104,/// 
    eERR_COMM_WIFI_INIT_CONFIG_UART_DATA      = 105,/// 
    eERR_COMM_WIFI_INIT_CONFIG_UART_BAUD      = 106,/// 
    eERR_COMM_WIFI_INIT_CONFIG_UART_FLOW = 107,/// 
    eERR_COMM_WIFI_INIT_CONFIG_UART_PARITY = 108,/// 
    eERR_COMM_WIFI_INIT_CONFIG_UART_STOP = 109,/// 
    eERR_COMM_WIFI_INIT_GET_MAC_ADDRESS = 110,/// 
    eERR_COMM_WIFI_INIT_CHECK_STATUS = 111,/// 
    eERR_COMM_WIFI_INIT_GET_VERSION = 112,/// 
    eERR_COMM_WIFI_INIT_NETWORK_UP = 113,/// 
    eERR_COMM_WIFI_INIT_NETWORK_DOWN = 114,/// 
    eERR_COMM_WIFI_INIT_SAVE_VARIABLES = 115,/// 
    eERR_COMM_WIFI_INIT_GET_IP_ADDRESS = 116,/// 
    eERR_COMM_WIFI_INIT_CACERT_FILE = 117,/// 
    eERR_COMM_WIFI_INIT_CACERT_OPEN = 118,/// 
    eERR_COMM_WIFI_INIT_CACERT_LENGTH = 119,/// 
    eERR_COMM_WIFI_INIT_CACERT_READ = 120,/// 
    eERR_COMM_WIFI_INIT_CONFIG_TLS_CACERT = 121,/// 
    eERR_COMM_WIFI_INIT_CONFIG_TLS_CACERT_OPEN = 122,/// 
    eERR_COMM_WIFI_INIT_CONFIG_TLS_CACERT_CLOSE = 123,/// 
    eERR_COMM_WIFI_INIT_CONFIG_TLS_CACERT_CREATE = 124,/// 
    eERR_COMM_WIFI_INIT_CONFIG_TLS_CACERT_DELETE = 125,/// 
    eERR_COMM_WIFI_TX_RX       = 126,/// 
    eERR_COMM_WIFI_TX_RX_GET_SERVER_ALIVE = 127,/// 
    eERR_COMM_WIFI_TX_RX_POST_INFO_DATA = 128,/// 
    eERR_COMM_WIFI_TX_RX_GET_UPGRADE_FILE  = 129,/// 
    eERR_COMM_WIFI_TX_RX_UPGRADE_FILE_OPEN = 130,/// 
    eERR_COMM_WIFI_TX_RX_UPGRADE_FILE_WRITE = 131,/// 
    eERR_COMM_WIFI_TX_RX_UPGRADE_FILE_FLUSH = 132,/// 
    eERR_COMM_WIFI_TX_RX_SEND_TCP_DATA = 133,/// 
    eERR_COMM_WIFI_TX_RX_SEND_UDP_DATA = 134,/// 
    eERR_COMM_WIFI_TX_RX_SEND_TLS_DATA = 135,/// 
    eERR_COMM_WIFI_TX_RX_GET_CONF_FILE = 136,/// 
    /// free to use            = 137,
    /// free to use            = 138,
    /// free to use            = 139,
    eERR_COMM_SIGFOX           = 140,/// 
    eERR_COMM_SIGFOX_STATUS    = 141,/// 
    eERR_COMM_SIGFOX_MAX_POWER  = 142,/// 
    eERR_COMM_SIGFOX_RX        = 143,/// 
    eERR_COMM_SIGFOX_TEST_TX_FREQ  = 144,/// 
    eERR_COMM_SIGFOX_TEST_RX_FREQ = 145,/// 
    eERR_COMM_SIGFOX_CW_TEST_START  = 146,/// 
    eERR_COMM_SIGFOX_CW_TEST_STOP = 147,/// 
    eERR_COMM_SIGFOX_RX_GFSK_TEST = 148,/// 
    /// free to use            = 149,
    eERR_COMM_GPS              = 150,/// 
    /// free to use            = 151,
    /// free to use            = 152,
    /// free to use            = 153,
    /// free to use            = 154,
    /// free to use            = 155,
    /// free to use            = 156,
    /// free to use            = 157,
    /// free to use            = 158,
    /// free to use            = 159,
    eERR_COMM_ACCELEROMETER    = 160,/// 
    eERR_COMM_ACC_WRITE_CTRL_REG1 = 161,/// 
    eERR_COMM_ACC_WRITE_CTRL_REG2 = 162,/// 
    eERR_COMM_ACC_WRITE_CTRL_REG4 = 163,/// 
    eERR_COMM_ACC_WRITE_CTRL_REG5 = 164,/// 
    eERR_COMM_ACC_WRITE_CTRL_REG6 = 165,/// 
    eERR_COMM_ACC_WRITE_INT2_CFG = 166,/// 
    eERR_COMM_ACC_WRITE_INT2_THS = 167,/// 
    eERR_COMM_ACC_WRITE_INT2_DURATION = 168,/// 
    eERR_COMM_ACC_WRITE_INT1_CFG = 169,/// 
    eERR_COMM_ACC_WRITE_INT1_THS = 170,/// 
    eERR_COMM_ACC_WRITE_INT1_DURATION = 171,/// 
    eERR_COMM_ACC_READ         = 172,/// 
    eERR_COMM_ACC_READ_PRESENCE = 173,/// 
    eERR_COMM_ACC_READ_XYZ_DATA = 174,/// 
    eERR_COMM_ACC_INT2         = 175,/// 
    /// free to use            = 176,
    /// free to use            = 177,
    /// free to use            = 178,
    /// free to use            = 179,
    eERR_KEYS                  = 180,/// 
    eERR_LEDS                  = 181,/// 
    /// free to use            = 182,
    /// free to use            = 183,
    /// free to use            = 184,
    /// free to use            = 185,
    /// free to use            = 186,
    /// free to use            = 187,
    /// free to use            = 188,
    /// free to use            = 189,
    eRR_EXPIRED_CERT_TLS       = 190,/// 
    eRR_EXPIRED_WPA_EAP        = 191,/// 
    eRR_NO_LOAD_CERT_TLS       = 192,/// 
    eRR_NO_LOAD_WPA_EAP        = 193,/// 
    /// free to use            = 194,
    /// free to use            = 195,
    /// free to use            = 196,
    /// free to use            = 197,
    /// free to use            = 198,
    /// free to use            = 199,
    /// free to use            = 200,
    /// free to use            = 201,
    /// free to use            = 202,
    /// free to use            = 203,
    /// free to use            = 204,
    /// free to use            = 205,
    /// free to use            = 206,
    /// free to use            = 207,
    /// free to use            = 208,
    /// free to use            = 209,
    /// free to use            = 210,
    /// free to use            = 211,
    /// free to use            = 212,
    /// free to use            = 213,
    /// free to use            = 214,
    /// free to use            = 215,
    /// free to use            = 216,
    /// free to use            = 217,
    /// free to use            = 218,
    /// free to use            = 219,
    /// free to use            = 220,
    /// free to use            = 221,
    /// free to use            = 222,
    /// free to use            = 223,
    /// free to use            = 224,
    /// free to use            = 225,
    /// free to use            = 226,
    /// free to use            = 227,
    /// free to use            = 228,
    /// free to use            = 229,
    /// free to use            = 230,
    /// free to use            = 231,
    /// free to use            = 232,
    /// free to use            = 233,
    /// free to use            = 234,
    /// free to use            = 235,
    /// free to use            = 236,
    /// free to use            = 237,
    /// free to use            = 238,
    /// free to use            = 239,
    /// free to use            = 240,
    /// free to use            = 241,
    /// free to use            = 242,
    /// free to use            = 243,
    /// free to use            = 244,
    /// free to use            = 245,
    /// free to use            = 246,
    /// free to use            = 247,
    /// free to use            = 248,
    /// free to use            = 249,
    /// free to use            = 250,
    /// free to use            = 251,
    /// free to use            = 252,
    /// free to use            = 253,
    /// free to use            = 254,
    eERR_END                   = MAX_ERRORS-1
} ERROR_ID_e;

#endif /* R100_ERRORS_H*/
/*-----------------------------------------------------------------------------*/
