name: Build C Project

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install build tools
      run: sudo apt-get install -y build-essential

    - name: Build project
      run: make
